### ISSUE TITLE
"Out of memory" issue

### ISSUE THREAD

**Issue by xiang-burlington** [TaoRuijie/TalkNet_ASD#21]
Thanks a lot for sharing your excellent work with us. Your code is really friending and the downloading process is painless. 

Here's the problem I encountered, while training talknet end-to-end with the command below:
python trainTalkNet.py --dataPathAVA AVADataPath
I got such error message:
RuntimeError: CUDA out of memory. Tried to allocate 1.87 GiB (GPU 0; 23.65 GiB total capacity; 6.17 GiB already allocated; 1.52 GiB free; 20.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Seems the 24GB memory of my titan rtx is not sufficient for the training task. Since I am still new to the code, I still have no idea where is the code that can be revised to reduce the GPU memory usage. would you minding telling me where to find the relevant code?

**Comment by xiang-burlington** [comment]
Update: I solved the issue by reduced the value of batchSize:
python trainTalkNet.py --dataPathAVA AVADataPath --batchSize 2000
